module.exports = [
  "Delhi",
  "New Delhi",
  "Mumbai",
  "Bengaluru",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Goa",
  "Agra",
  "Varanasi",
  "Udaipur",
  "Jodhpur",
  "Jaisalmer",
  "Shimla",
  "Manali",
  "Dharamshala",
  "Rishikesh",
  "Haridwar",
  "Dehradun",
  "Mussoorie",
  "Amritsar",
  "Chandigarh",
  "Lucknow",
  "Kanpur",
  "Prayagraj",
  "Noida",
  "Gurugram",
  "Faridabad",
  "Ghaziabad",
  "Kochi",
  "Munnar",
  "Alleppey",
  "Thiruvananthapuram",
  "Kozhikode",
  "Mysuru",
  "Coorg",
  "Hampi",
  "Gokarna",
  "Ooty",
  "Kodaikanal",
  "Madurai",
  "Pondicherry",
  "Mahabalipuram",
  "Visakhapatnam",
  "Vijayawada",
  "Tirupati",
  "Bhubaneswar",
  "Puri",
  "Darjeeling",
  "Gangtok",
  "Shillong",
  "Guwahati",
  "Kaziranga",
  "Aizawl",
  "Imphal",
  "Kohima",
  "Itanagar",
  "Raipur",
  "Bhopal",
  "Indore",
  "Gwalior",
  "Khajuraho",
  "Nagpur",
  "Nashik",
  "Aurangabad",
  "Lonavala",
  "Mahabaleshwar",
  "Surat",
  "Vadodara",
  "Rajkot",
  "Dwarka",
  "Rann of Kutch",
  "Srinagar",
  "Gulmarg",
  "Leh",
  "Ladakh",
  "Port Blair",
  "Lakshadweep",
  "Patna",
  "Ranchi",
  "Jamshedpur",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];
